### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by Emilprivate** [SoftwareGroup305-AAU/P4#7]
Expanding this section to include project workflow with GitHub.

**Comment by mLario1999** [comment]
- [ ]  hee

- [ ]  hoo

- [ ]  bitch

**Comment by Kragemand** [comment]
Todo:

- [ ] Methodology and configuration management
- [ ] Revision of problem analysis
- [ ] Language design and definition
- [ ] Compiler theory and design, and Antlr
- [ ] Implementation, AST, Typechecker, Codegen
- [ ] Testing, grammar fixes
- [ ] Deprecated code, Liveness analysis and asm implementation
- [ ] Discussion, asm, arm, arduino, linking, testing
- [ ] Conclusion
